[package]
name = "cxx-qt"
version = "0.1.0"
authors = ["Andrew Hayzen <andrew.hayzen@kdab.com>", "Gerhard de Clercq <gerhard.declercq@kdab.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.4"
indoc = "1.0"
itertools = "0.10"
syn = { version = "1.0", features = ["extra-traits", "full"] }
quote = "1.0"
proc-macro2 = "1.0"
derivative = "2.2"

[dev-dependencies]
pretty_assertions = "0.7"
